name: 'LINE-in-action'
description: 'Github action for pushing LINE message using LINE-Notify'
author: 'raeperd'
inputs:
  token:
    required: true
    description: An access token for authentication. Used for calling the notification API
  notificationDisabled:
    required: false
    description: If true, user doesn't receive a push notification when the message is sent.
                 If false, The user receives a push notification when the message is sent.
                 If omitted, the value defaults to false.
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
